### ISSUE TITLE
elm-doc-preview can get confused if multiple files are modified simultaneously

### ISSUE THREAD

**Issue by ianmackenzie** [dmy/elm-doc-preview#33] opened 2020-02-11 02:27 UTC
I ran into this when working on a new package of testing utilities for `elm-geometry`, where all the modules are simply copied over from `elm-geometry` using a script. Doing so seems to confuse `elm-doc-preview` if it's running a server at the time the files are copied over - one time it only noticed that one file had changed and so didn't update another, and another time the server crashed with

```
Error: EPERM: operation not permitted, lstat 'C:\Git\ianmackenzie\elm-geometry-test\rm-5'
```

Not a critical issue and probably a very rare use case, but I thought I'd mention it!

**Comment by rlefevre** [comment] 2020-04-06 22:20
I have reworked the file watcher using `chokidar` instead of `sane` in version `5.0.0` to remove a lot of dependencies and fix a few issues. I think your issue might be fixed by these changes but I was not able to reproduce it exactly so I'm not sure.

I will therefore close the bug, but please reopen if you encounter this issue again.

**Closed by rlefevre** 2020-04-06 22:20 UTC
Labels: bug
